/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/scene.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.greyUnderside} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.whiteFloor} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.blackStreet} />
      <group position={[0, 1.009, -0.372]}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.wall} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.Light} />
        <mesh geometry={nodes.Plane003.geometry} material={materials.neonRed} position={[0, 3.605, 0]} scale={0.88} />
        <mesh geometry={nodes.Plane005.geometry} material={materials.wall} position={[0, 3.299, 0]} scale={0.88} />
        <mesh geometry={nodes.Plane006.geometry} material={materials.innerWall} scale={0.88} />
        <mesh geometry={nodes.Plane007.geometry} material={materials.innerWall} scale={0.88} />
        <mesh geometry={nodes.Plane008.geometry} material={materials.red} />
      </group>
      <mesh geometry={nodes.bricks.geometry} material={materials.brick} position={[-2.898, 3.228, 0.275]} rotation={[0, Math.PI / 2, 0]} scale={[0.224, 0.092, 0.042]} />
      <mesh geometry={nodes.bottomBun.geometry} material={materials.bottomBun} position={[0.011, 4.735, -0.383]} />
      <mesh geometry={nodes.burger001.geometry} material={materials.burger} position={[0.011, 6.07, -0.383]} rotation={[0, 1.278, 0]} />
      <mesh geometry={nodes.burger002.geometry} material={materials['burger.001']} position={[0.011, 5.257, -0.383]} rotation={[0, 1.278, 0]} />
      <mesh geometry={nodes.Cheese001.geometry} material={materials.cheese} position={[0.015, 6.273, -0.394]} rotation={[0, 1.278, 0]} />
      <mesh geometry={nodes.Cheese002.geometry} material={materials.cheese} position={[0.021, 5.46, -0.389]} rotation={[0, 0.563, 0]} />
      <mesh geometry={nodes.lettuce001.geometry} material={materials.lettuce} position={[0.011, 4.988, -0.383]} />
      <mesh geometry={nodes.lettuce003.geometry} material={materials.lettuce} position={[0.012, 5.707, -0.384]} />
      <mesh geometry={nodes.onion01.geometry} material={materials.onion} position={[-0.545, 6.485, -0.537]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.tomato02.geometry} material={materials.tomato} position={[-0.54, 5.81, 0.045]} rotation={[-Math.PI, -0.779, 0]} />
      <mesh geometry={nodes.topbun.geometry} material={materials.topBun} position={[0.011, 6.901, -0.383]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
